version: "1.1"
pipeline:
  name: bodywork-scikit-fastapi-project
  docker_image: bodyworkml/bodywork-core:3.0
  DAG: scoring-service
stages:
  scoring-service:
    executable_module_path: serve_model.py
    requirements:
      - fastapi==0.63.0
      - joblib==1.0.1
      - numpy==1.20.2
      - scikit-learn==0.24.1
      - uvicorn==0.13.4
    cpu_request: 0.5
    memory_request_mb: 250
    service:
      max_startup_time_seconds: 120
      replicas: 2
      port: 8000
      ingress: true
logging:
  log_level: INFO
